### ISSUE TITLE
Any plan for training code example?

### ISSUE THREAD

**Issue by KIMGEONUNG** [VITA-Group/NeuralLift-360#1]
Hello, at first, thank you for awesome work and code share.

I think this repository doen't include training code example.
Is there any plan to share training code example?
If so, it would be very helpful to many researchers in this domain.

thank you.

**Comment by Ir1d** [comment]
@KIMGEONUNG Thanks for the interest, I'll release the codebase after ICCV deadline

**Comment by Ir1d** [comment]
Hi @KIMGEONUNG @wukailu @terryryu sorry for the long wait. We've released the code for our basic workflow and will continue to refine the repo with more features! 🙏
