### ISSUE TITLE
The background of the rendered images

### ISSUE THREAD

**Issue by hzhupku** [VITA-Group/NeuralLift-360#2]
Thank you for the work. I am just curious why the background of the rendered images differs from the reference image.

**Comment by Ir1d** [comment]
Hi @hzhupku Thanks for your interest. Generating 3D at scene level (for background) is still an open question. In our work we follow the implementation in DreamFusion where we use an additional background mlp to fuse the information less related to the object. The background mlp is not constrained to look like the reference image for now.
