### ISSUE TITLE
Add the specify version of pkgs in the requirements file?

### ISSUE THREAD

**Issue by xuhaowork** [VITA-Group/NeuralLift-360#3]
Can you add the specify version of pkgs in the requirements file? And also the python version.
It's two hard for me to handle compatibility issues of python dependent packages~~

**Comment by Ir1d** [comment]
Hi @xuhaowork  Thanks for your interest. I've added a conda environment file. You can replicate the environment with 

```
conda env create -f environment.yml
```

**Comment by keithcallenberg** [comment]
Using that environment.yml I get an error that there is no 1.0 release of `clip` in pypi
