### ISSUE TITLE
the difference between SDS loss and diffusion loss at section 4.2

### ISSUE THREAD

**Issue by yanxinhao** [VITA-Group/NeuralLift-360#4]
I notice some distinctions in the implementation. In the released paper, the predicted sigma in Equation 10 includes three terms. I am confused about its mathematical derivation, and it becomes sds loss instead in the codes. If wonder if there are distinct performances during the mode seeking. I would be grateful if you could help explain the derivation.

**Comment by Ir1d** [comment]
Hi @yanxinhao , thanks for your interest.

![image](https://user-images.githubusercontent.com/10709657/231627967-c4f5a655-3d50-4b49-9812-ef52238079cf.png)
In Eq (10) the first two term is the classifier free guidance. The last term is the classifier guidance implemented with CLIP loss. 
Please feel free to let me know if there are additional questions
