### ISSUE TITLE
the depth in data doesn't align with the rgb and mask

### ISSUE THREAD

**Issue by yanxinhao** [VITA-Group/NeuralLift-360#5]
I found the file cabin4_centered.npy doesn't align with the rgb and mask. Here are the visualizations and maybe it is a bug.
![cabin4_centered_mask](https://user-images.githubusercontent.com/22325218/231411895-fd8d30cc-be49-4587-b798-316b818dbbba.png)
![cabin4_centered_depth](https://user-images.githubusercontent.com/22325218/231411913-38607c18-3b36-463e-ae22-dc705b93a1d8.png)
![cabin4_centered](https://user-images.githubusercontent.com/22325218/231411919-11c2582d-f4dc-446d-b54b-e5fd76113173.png)

**Comment by Ir1d** [comment]
Really appreciate it! I've uploaded the correct files now. 🙏
