### ISSUE TITLE
Training out of Memory

### ISSUE THREAD

**Issue by Seasandwpy** [VITA-Group/NeuralLift-360#7]
Hi, I am trying to train the default setting with a 16GB GPU, however, I always get the CUDA out of memory error, even if I shrink the camera width and height to 64. Is it possible to test some training with limited gpu memory?

**Comment by Ir1d** [comment]
Hi @Seasandwpy thanks for your interest. We can reduce the patch size by reducing these three configs https://github.com/VITA-Group/NeuralLift-360/blob/main/configs/cabin.yaml#L38-L40 Don't forget to reduce the normal_shape
